### ISSUE TITLE
ERROR: SNAKEFILE 

### ISSUE THREAD

**Issue by Carly-31** [BleekerLab/small-rna-seq-pipeline#11]
Hello I am new to snakemake and I am having a problem I followed everything outline for the installation process but I am getting this error: 

WorkflowError in line 16 of /mnt/h/sRNA-snake/Snakefile:
Config file is not valid JSON or YAML. In case of YAML, make sure to not mix whitespace and tab indentation.
  File "/mnt/h/sRNA-snake/Snakefile", line 16, in <module>

**Comment by mgalland** [comment]
Hello Carly, 
That's a YAML-related error. You can check your config file YAML format using an online YAML tool. Copy paste your YAML file and check that it's format is ok. 
Cheers
Marc
http://www.yamllint.com/
